# Generated by Django 3.2.18 on 2023-05-05 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simpl.utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.SIMPL_RUN),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpl', '0020_auto_20211109_2056'),
        migrations.swappable_dependency(settings.SIMPL_GAME_EXPERIENCE),
        migrations.swappable_dependency(settings.SIMPL_CHARACTER),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWithRelatedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(blank=True, default=dict, editable=False)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.SIMPL_GAME_EXPERIENCE)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerswithrelatedname', to=settings.SIMPL_RUN)),
            ],
            options={
                'ordering': ('-date_created',),
                'abstract': False,
            },
            bases=(simpl.utils.models.DataMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready', models.BooleanField(default=True)),
                ('inactive', models.BooleanField(default=False)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.SIMPL_CHARACTER)),
                ('lobby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpl.lobby')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.SIMPL_RUN)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
