# Generated by Django 2.2.22 on 2021-10-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simpl", "0018_apitoken_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameexperience",
            name="allow_facilitator_continuous_management",
            field=models.NullBooleanField(
                default=True,
                help_text="Allow facilitators to disable enrollment for continuous runs. If unset, this becomes configurable at the run level.",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="allow_facilitator_continuous_management",
            field=models.BooleanField(
                default=True,
                help_text="Allow facilitators to disable enrollment for continuous runs.",
            ),
        ),
        migrations.AlterField(
            model_name="gameexperience",
            name="continuous",
            field=models.BooleanField(
                blank=True,
                help_text="Whether players can join after a run is in play. If unset, this becomes configurable at the run level.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gameexperience",
            name="multiplayer",
            field=models.BooleanField(
                blank=True,
                help_text="Whether multiple players play a single instance of the game. If unset, this becomes configurable at the run level.",
                null=True,
            ),
        ),
    ]
